services:
  cvdupdate:
    image: maneeshuh/cvdupdate-exp:latest
    volumes:
      - signatures:/clamav

  nginx:
    image: nginx:alpine
    depends_on:
      - cvdupdate
    container_name: clamav-nginx
    ports:
      - "8800:80"
    volumes:
      - signatures:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  signatures:

